import type { Timestamp } from "firebase/firestore";

export type UserRole = "player" | "coach" | "both";

/** Top-level user profile, keyed by uid. */
export type UserProfile = {
  uid: string;
  email: string | null;
  displayName: string | null;
  photoUrl: string | null;
  role: UserRole;
  /** Optional handicap for player matching. */
  handicap?: number | null;
  /** Free-text home course / city for matching. */
  location?: string | null;
  /**
   * Set to true after the user completes the role-selection onboarding step.
   * New accounts (and first-time Google sign-ins) leave this undefined/false,
   * which triggers a redirect to /onboard.
   */
  onboarded?: boolean;
  createdAt: Timestamp;
  updatedAt: Timestamp;
};

/** Public coach profile, keyed by uid. Readable by anyone signed in. */
export type CoachProfile = {
  uid: string;
  displayName: string;
  bio?: string;
  /** PGA, LPGA, R&A, certifications etc. */
  credentials?: string[];
  /** Years of teaching experience. */
  yearsCoaching?: number | null;
  /** Free-text style: e.g. "video-based", "feel-based", "data-driven". */
  teachingStyle?: string;
  /** Free-text specialties: short game, mental, juniors etc. */
  specialties?: string[];
  /** Optional public-facing rate, freeform string ("$80/hr"). */
  rate?: string;
  location?: string;
  photoUrl?: string | null;
  /** Whether the coach wants to be discoverable in browse / search. */
  acceptingPlayers: boolean;
  createdAt: Timestamp;
  updatedAt: Timestamp;
};

/** A short-lived 6-character pairing code generated by a coach. */
export type PairingCode = {
  code: string;
  coachId: string;
  coachDisplayName: string;
  createdAt: Timestamp;
  expiresAt: Timestamp;
  used: boolean;
  usedBy?: string | null;
  usedAt?: Timestamp | null;
};

export type PairingStatus = "active" | "revoked";

/**
 * Active link between a coach and a player. Doc id is deterministic:
 * `${coachId}__${playerId}` so we cannot create duplicates.
 */
export type Pairing = {
  id: string;
  coachId: string;
  playerId: string;
  /** The pairing code consumed to create this link. Used by security rules. */
  codeUsed: string;
  status: PairingStatus;
  pairedAt: Timestamp;
  /** Snapshots of names for fast display in lists without extra reads. */
  playerDisplayName?: string;
  coachDisplayName?: string;
};

export const PAIRING_CODE_LENGTH = 6;
export const PAIRING_CODE_TTL_MS = 10 * 60 * 1000; // 10 minutes
